# Generated by Django 4.2.21 on 2025-05-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='landmarks/'),
        ),
    ]
