# Generated by Django 4.2.21 on 2025-05-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0002_alter_landmark_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='category',
            field=models.CharField(blank=True, choices=[('RELIGIOUS', 'Religious Tourism'), ('HISTORICAL', 'Historical'), ('NATURAL', 'Natural'), ('CULTURAL', 'Cultural'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
