# Generated by Django 4.2.21 on 2025-06-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0002_alter_landmark_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
